pipeline {
    agent any

    environment {
        REGISTRY_PASSWORD_1 = credentials('REGISTRY_PASSWORD_1')
        group='rg-devops-sura-damir1-dev'
        location='southcentralus'
        registry='crdevopssuradamir1dev'
        registry_url='https://crdevopssuradamir1dev.azurecr.io'
        skuRegistry='Basic'
        plan='plan-devops-sura-damir1-dev'
        app='app-devops-sura-starter-damir1-dev'
        image='crdevopssuradamir1dev.azurecr.io/starter:latest'
    }

    stages {
        stage('Checkout') { 
            steps {
                // 
                echo 'Checking out'
                sh 'sudo apt-get update -y'
                sh 'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash'
                nodejs(nodeJSInstallationName: 'Node 12.22.3') {
                    sh 'rm -rf fe-devops-sura-damir1-dev'
                    sh 'npx gatsby new fe-devops-sura-damir1-dev https://github.com/Evaluates2/Gatsby-Starter-TypeScript-Redux-TDD-BDD'
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                nodejs(nodeJSInstallationName: 'Node 12.22.3') {
                    sh '''
                     npx sonar-scanner \
                    -Dsonar.host.url=http://vm-devops-sura-sonarqube-damir1-dev.southcentralus.cloudapp.azure.com/ \
                    -Dsonar.login=$ToA \
                    -Dsonar.sources=./fe-devops-sura-damir1-dev \
                    -Dsonar.exclusions=./fe-devops-sura-damir1-dev/node_modules \
                    -Dsonar.projectName=DevOps \
                    -Dsonar.projectKey=DevOps                    
                    '''                
                }
            }
        }
        stage('Build') { 
            steps {
                // 
                echo 'Building'
                nodejs(nodeJSInstallationName: 'Node 12.22.3') {
                    sh 'npm run build --prefix fe-devops-sura-damir1-dev'
                }
            }
        }
        stage('Test') { 
            steps {
                // 
                echo 'Testing'
                nodejs(nodeJSInstallationName: 'Node 12.22.3') {
                    sh 'npm run test-once --prefix fe-devops-sura-damir1-dev'
                    sh 'npm run lint --prefix fe-devops-sura-damir1-dev'
                }
            }
        }
        stage('Delivery') { 
            steps {
                // 
                echo 'Deliverying'
                withCredentials([azureServicePrincipal('8e8fff0b-fe2a-4ff7-a6d6-3863c0242d3e')]) {
                    sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
                    sh '''
cat <<-EOF> fe-devops-sura-damir1-dev/Dockerfile
FROM nginx:stable-alpine
COPY public /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
EOF'''
                    sh 'docker build -f fe-devops-sura-damir1-dev/Dockerfile -t $image fe-devops-sura-damir1-dev'
                    sh 'docker login $registry_url -u crdevopssuradamir1dev -p $REGISTRY_PASSWORD_1'
                    sh 'docker push $image'
                }
            }
        }
        stage('Deploy') { 
            steps {
                // 
                echo 'Deploying'
                sh 'az configure --defaults group=$group location=$location'
                sh 'az webapp create --plan $plan --name $app --deployment-container-image-name $image'
                sh 'az webapp config container set --name $app --docker-custom-image-name $image --docker-registry-server-url $registry_url'
            }
        }
    }
}
